let stockProductos = [
    { id: 1, nombre: "Acido Hialuronico", cantidad: 1, desc: "Ideal para las arrugas", precio: 2200, piel: "Seca", img: `./img/acid.jpg` },
    { id: 2, nombre: "Acido Hialuronico", cantidad: 1, desc: "Ideal para las arrugas", precio: 2300, piel: "Mixta", img: `./img/acid.jpg` },
    { id: 3, nombre: "Aceite Cannabis", cantidad: 1, desc: "Analgesico Natural", precio: 1400, piel: "Seca", img: `./img/aceite.jpg` },
    { id: 4, nombre: "Aceite Cannabis", cantidad: 1, desc: "Analgesico Natural", precio: 1500, piel: "Grasa", img: `./img/aceite.jpg` },
    { id: 5, nombre: "Acondicionador", cantidad: 1, desc: "Sin aditivos!! ", precio: 1900, piel: "Seco", img: `./img/acond.png` },
    { id: 6, nombre: "Acondicionador", cantidad: 1, desc: "Eco Friendly", precio: 1950, piel: "Graso", img: `./img/acond.png` },
    { id: 7, nombre: "Combo + Jabonera", cantidad: 1, desc: "Aprovecha esta oferta!", precio: 1750, piel: "Seca", img: `./img/combo2.jpg` },
    { id: 8, nombre: "Combo + Jabonera", cantidad: 1, desc: "Aprovecha esta oferta!", precio: 1750, piel: "Grasa", img: `./img/combo2.jpg` },
    { id: 9, nombre: "Desodorante Natural", cantidad: 1, desc: "No deja manchas!", precio: 900, piel: "Seca", img: `./img/deso.jpg` },
    { id: 10, nombre: "Desodorante Natural", cantidad: 1, desc: "No obstruye los poros", precio: 950, piel: "Grasa", img: `./img/deso.jpg` },
    { id: 11, nombre: "Mascarilla Facial", cantidad: 1, desc: "Para Pieles grasas", precio: 3000, piel: "Grasa", img: `./img/masca.jpg` },
    { id: 12, nombre: "Mascarilla Facial", cantidad: 1, desc: "Para pieles sensibles", precio: 3200, piel: "Mixta", img: `./img/masca.jpg` },
    { id: 13, nombre: "Crema Nicacinamida", cantidad: 1, desc: "Ultimos en stock!!", precio: 4100, piel: "Grasa", img: `./img/niaci.jpeg` },
    { id: 14, nombre: "Crema Nicacinamida", cantidad: 1, desc: "Ultimos en stock!!", precio: 4250, piel: "Seca", img: `./img/niaci.jpeg` },
    { id: 15, nombre: "Shampoo Solido", cantidad: 1, desc: "Biodegradables", precio: 650, piel: "Seca", img: `./img/shampoo.jpeg` },
    { id: 16, nombre: "Shampoo Solido", cantidad: 1, desc: "100% Artesanal", precio: 650, piel: "Mixta", img: `./img/shampoo.jpeg` },
]  